// CJK font pipeline (guide「字体与 CJK 加载」): slice OFL sources with cn-font-split into
// unicode-range woff2 chunks under public/fonts, then write public/fonts/cjk.css with
// absolute URLs.
// Usage: pnpm fonts:cjk   (sources are downloaded into fonts-src/, which is gitignored)
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Character set: GB 2312 (6,763 hanzi + symbols) plus CJK punctuation and fullwidth forms.
// Latin never renders in these fonts (Fraunces/Geist come first in every stack), and rarer
// hanzi fall back to PingFang SC / Microsoft YaHei. Keeps the @font-face CSS small.
function charset() {
  const dec = new TextDecoder('gbk');
  const out = new Set<string>();
  for (let b1 = 0xa1; b1 <= 0xf7; b1++)
    for (let b2 = 0xa1; b2 <= 0xfe; b2++) {
      const ch = dec.decode(new Uint8Array([b1, b2]));
      if (ch !== '\ufffd') out.add(ch);
    }
  const ranges: [number, number][] = [[0x3000, 0x303f], [0xff00, 0xff65], [0x2010, 0x2027], [0x00b7, 0x00b7]];
  for (const [a, b] of ranges) for (let c = a; c <= b; c++) out.add(String.fromCodePoint(c));
  return [...out].join('');
}

/** Subset with fontTools (python3 -m pip install fonttools). */
function subset(src: string, chars: string) {
  const textFile = join('fonts-src', 'charset.txt');
  writeFileSync(textFile, chars);
  const out = src.replace(/\.(otf|ttf)$/, '.subset.$1');
  execFileSync('python3', ['-m', 'fontTools.subset', src, `--text-file=${textFile}`, `--output-file=${out}`,
    '--layout-features=*', '--no-hinting', '--desubroutinize'], { stdio: 'inherit' });
  return out;
}

const FONTS = [
  {
    dir: 'noto-serif-sc',
    family: 'Noto Serif SC',
    weight: '600',
    display: 'swap',
    sheet: 'cjk.css',
    // Chrome's local() matches full or PostScript names, not family names.
    local: ['Noto Serif SC SemiBold', 'NotoSerifSC-SemiBold', 'Noto Serif CJK SC SemiBold', 'NotoSerifCJKsc-SemiBold', 'SourceHanSerifSC-SemiBold'],
    file: 'NotoSerifSC-SemiBold.otf',
    url: 'https://github.com/notofonts/noto-cjk/raw/main/Serif/SubsetOTF/SC/NotoSerifSC-SemiBold.otf',
  },
  {
    dir: 'noto-sans-sc',
    family: 'Noto Sans SC',
    weight: '400',
    // Body text: never delay LCP or reflow — if a slice isn't ready within ~100 ms the system
    // CJK font stays for this page view and the slice is used from cache next time.
    display: 'optional',
    sheet: 'cjk.css',
    // System copies first: Apple (PingFang SC) and Android (Noto Sans CJK SC) download nothing;
    // Windows/Linux get the Noto slices. Calibrated against the zh first-screen budget.
    local: ['PingFang SC Regular', 'PingFangSC-Regular', 'Noto Sans CJK SC Regular', 'NotoSansCJKsc-Regular', 'Noto Sans SC Regular', 'NotoSansSC-Regular', 'SourceHanSansSC-Regular'],
    file: 'NotoSansSC-Regular.otf',
    url: 'https://github.com/notofonts/noto-cjk/raw/main/Sans/SubsetOTF/SC/NotoSansSC-Regular.otf',
  },
  {
    dir: 'lxgw-wenkai',
    family: 'LXGW WenKai',
    weight: '400',
    display: 'swap',
    sheet: 'cjk-note.css', // only CuratorNote uses it; injected after load by NoteFontLoader
    local: ['LXGW WenKai Regular', 'LXGWWenKai-Regular'],
    file: 'LXGWWenKai-Regular.ttf',
    url: 'https://github.com/lxgw/LxgwWenKai/releases/latest/download/LXGWWenKai-Regular.ttf',
  },
] as const;

async function ensureSource(file: string, url: string) {
  const path = join('fonts-src', file);
  if (existsSync(path)) return path;
  mkdirSync('fonts-src', { recursive: true });
  console.log(`downloading ${file}`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  writeFileSync(path, Buffer.from(await res.arrayBuffer()));
  return path;
}

async function main() {
  const { fontSplit } = await import('cn-font-split');
  const chars = charset();
  console.log(`charset: ${chars.length} characters`);
  const header = '/* Generated by scripts/fonts-cjk.ts (cn-font-split). Do not edit by hand. */';
  const sheets = new Map<string, string[]>();
  for (const f of FONTS) {
    const src = subset(await ensureSource(f.file, f.url), chars);
    const outDir = join('public', 'fonts', f.dir);
    rmSync(outDir, { recursive: true, force: true });
    await fontSplit({
      input: new Uint8Array(readFileSync(src)),
      outDir,
      css: { fontFamily: f.family, fontWeight: f.weight, fontStyle: 'normal', fontDisplay: f.display, compress: true, localFamily: [...f.local] },
      chunkSize: 16 * 1024, // smaller chunks → fewer unused glyphs per page (HTTP/2 makes requests cheap)
      testHtml: false,
      reporter: false,
      silent: true,
      renameOutputFont: '[hash:8].[ext]',
    });
    const css = readFileSync(join(outDir, 'result.css'), 'utf8')
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(
      /url\((["']?)\.?\/?([^"')]+\.woff2)\1\)/g,
      (_m, _q, name: string) => `url("/fonts/${f.dir}/${name}")`,
    );
    rmSync(join(outDir, 'result.css'));
    const list = sheets.get(f.sheet) ?? [header];
    list.push(`/* ${f.family} ${f.weight} */`, css.trim());
    sheets.set(f.sheet, list);
    console.log(`${f.family}: done`);
  }
  // Served as a static stylesheet and linked only on zh pages and /admin (see [locale]/layout.tsx),
  // so English pages never pay for CJK @font-face rules.
  for (const [name, list] of sheets) writeFileSync(join('public', 'fonts', name), `${list.join('\n')}\n`);
}

main()
  .then(() => process.exit(0)) // cn-font-split's FFI handle keeps the event loop alive
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
