"""Emit SVG outlines of the template-cover glyphs (PRD §5b step 3) from Noto Serif SC SemiBold,
so the tile never waits for a font slice. Usage: python3 scripts/glyph-paths.py > src/lib/covers/glyphs.ts"""
import json
import sys
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont

SRC = sys.argv[1] if len(sys.argv) > 1 else 'fonts-src/NotoSerifSC-SemiBold.otf'
font = TTFont(SRC)
gs = font.getGlyphSet()
cmap = font.getBestCmap()
out = {}
for ch in '黑投校会骑聚':
    g = gs[cmap[ord(ch)]]
    pen = SVGPathPen(gs)
    g.draw(pen)
    bp = BoundsPen(gs)
    g.draw(bp)
    x0, y0, x1, y1 = bp.bounds
    out[ch] = {'d': pen.getCommands(), 'box': [x0, y0, x1, y1]}
print('// Generated by scripts/glyph-paths.py from Noto Serif SC SemiBold (OFL). Do not edit.')
print('// Font units (1000/em), y axis up. Box = [xMin, yMin, xMax, yMax].')
print('export const GLYPHS: Record<string, { d: string; box: [number, number, number, number] }> = ' + json.dumps(out, ensure_ascii=False) + ';')
