// Vendor VTIMEZONE components for the zones events realistically use, so the ICS routes never
// read files at runtime (pnpm's symlinked node_modules can't be traced into a Vercel function).
// Usage: pnpm tz:vendor
import { writeFileSync } from 'node:fs';
import { getVtimezoneComponent } from '@touch4it/ical-timezones';

const ZONES = [
  'America/Los_Angeles', 'America/Denver', 'America/Phoenix', 'America/Chicago', 'America/New_York',
  'Pacific/Honolulu', 'America/Anchorage', 'Europe/London', 'Europe/Paris', 'Europe/Berlin',
  'Asia/Shanghai', 'Asia/Hong_Kong', 'Asia/Taipei', 'Asia/Tokyo', 'Asia/Singapore', 'Asia/Kolkata', 'Etc/UTC',
];

const map: Record<string, string> = {};
for (const z of ZONES) {
  const c = getVtimezoneComponent(z);
  if (!c) throw new Error(`no VTIMEZONE for ${z}`);
  map[z] = c.trim();
}
writeFileSync(
  'src/lib/vtimezones.ts',
  `// Generated by scripts/vtimezones.ts from @touch4it/ical-timezones (tzurl.org data). Do not edit.\n` +
    `const VTIMEZONES: Record<string, string> = ${JSON.stringify(map, null, 2)};\n\n` +
    `/** ical-generator timezone generator; null for zones we don't vendor (clients know IANA ids). */\n` +
    `export function vtimezone(tz: string): string | null {\n  return VTIMEZONES[tz] ?? null;\n}\n`,
);
console.log(`vendored ${ZONES.length} zones`);
